import "server-only";
import { v2 as cloudinary } from "cloudinary";
import { resolveResourceType, buildPublicId } from "./resource-type";

export { resolveResourceType, buildPublicId };

/**
 * Storage backend, per explicit decision: Cloudinary, not Firebase
 * Storage. This is a deliberate replacement, not an addition — the
 * original spec (§1, §4) assumed Firebase Storage throughout, but
 * Cloudinary has no equivalent to Firestore Security Rules (no
 * declarative, claims-based access control engine). The access-control
 * posture this module reconstructs to compensate:
 *
 *   1. SIGNED UPLOADS ONLY (explicit decision) — every upload requires
 *      a signature generated server-side by getUploadSignature() below,
 *      which only runs after the same requireServerSession() +
 *      hasPermission() + state-machine checks every other mutation in
 *      this codebase already does (see app/actions/versions.ts). There
 *      is no unsigned upload preset configured or used anywhere.
 *   2. type: "authenticated" on every uploaded asset — Cloudinary
 *      assets uploaded with this access type are NOT publicly
 *      reachable by their plain URL; downloading requires a signed URL
 *      with an expiry, generated by getAuthenticatedAssetUrl() below.
 *      This is the closest Cloudinary equivalent to Firebase Storage's
 *      rules-gated downloads — re-derived per request, not a
 *      fire-and-forget public link.
 *   3. public_id is deterministic and org-scoped
 *      (organizations/{orgId}/documents/{documentId}/v{N}), mirroring
 *      the exact same path convention the old Firebase Storage
 *      integration used.
 *
 * None of this is enforced by Cloudinary itself the way Firestore
 * Security Rules enforce tenant isolation independently of application
 * code — it is enforced by THIS APPLICATION'S server actions being the
 * only code path that ever calls these functions. There is no
 * declarative backstop equivalent to storage.rules anymore; the
 * discipline has to hold in code review, the same caveat §4 already
 * states applies to Firestore's Admin SDK bypass.
 */

function ensureConfigured() {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey = process.env.CLOUDINARY_API_KEY;
  const apiSecret = process.env.CLOUDINARY_API_SECRET;

  if (!cloudName || !apiKey || !apiSecret) {
    throw new Error(
      "Missing Cloudinary credentials. Set CLOUDINARY_CLOUD_NAME, " +
        "CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET in your environment. " +
        "See .env.example."
    );
  }

  cloudinary.config({
    cloud_name: cloudName,
    api_key: apiKey,
    api_secret: apiSecret,
    secure: true,
  });

  return { apiSecret };
}

export interface UploadSignaturePayload {
  cloudName: string;
  apiKey: string;
  timestamp: number;
  signature: string;
  publicId: string;
  folder: string;
  type: "authenticated";
  resourceType: "image" | "raw";
}

/**
 * Generates a signed-upload payload for the client to use directly
 * against Cloudinary's upload API. The client never sees the API
 * secret — only the signature, which is a one-way hash of the exact
 * parameters being signed plus the secret. If the client tampers with
 * any signed parameter before uploading, Cloudinary rejects the upload
 * with a signature mismatch.
 *
 * resourceType is determined HERE, server-side, from the file's
 * declared MIME type (via resolveResourceType) — not left for
 * Cloudinary's /auto/upload endpoint to decide, because the client
 * needs to know in advance which endpoint URL to POST to
 * (.../image/upload vs .../raw/upload), and because document_versions
 * needs a definite resourceType value to later generate a correctly-
 * typed download/preview URL. resource_type itself is NOT part of the
 * signed parameters (Cloudinary's signing scheme ties it to the
 * endpoint URL the client uploads to, not to a signable form field) —
 * the signature only covers public_id/timestamp/type, but the
 * SERVER-DETERMINED resourceType returned here is what the client must
 * use to pick that endpoint, and recordUploadedVersion() independently
 * re-derives the same resourceType from the same mimeType server-side
 * when persisting the version row, so the two can never disagree.
 *
 * Callers (see app/actions/versions.ts getUploadSignatureForVersion)
 * MUST have already run requireServerSession() + hasPermission() +
 * state-machine checks before calling this — this function itself does
 * not check anything; permission checks belong in the Server Action,
 * not in the storage-layer helper.
 */
export function getUploadSignature(params: {
  orgId: string;
  documentId: string;
  revisionNumber: number;
  mimeType: string;
}): UploadSignaturePayload {
  const { apiSecret } = ensureConfigured();

  const publicId = buildPublicId(params.orgId, params.documentId, params.revisionNumber);
  const folder = `organizations/${params.orgId}/documents/${params.documentId}`;
  const timestamp = Math.floor(Date.now() / 1000);
  const resourceType = resolveResourceType(params.mimeType);

  // Every parameter listed here MUST also be sent by the client at
  // upload time, with IDENTICAL values — Cloudinary recomputes the
  // signature server-side from whatever the client actually sent and
  // compares it. type: "authenticated" is what keeps the uploaded file
  // from being publicly downloadable by guessing/constructing its URL.
  const paramsToSign = {
    public_id: publicId,
    timestamp,
    type: "authenticated" as const,
  };

  const signature = cloudinary.utils.api_sign_request(paramsToSign, apiSecret);

  return {
    cloudName: process.env.CLOUDINARY_CLOUD_NAME!,
    apiKey: process.env.CLOUDINARY_API_KEY!,
    timestamp,
    signature,
    publicId,
    folder,
    type: "authenticated",
    resourceType,
  };
}

/**
 * Generates a time-limited signed URL for downloading/previewing an
 * authenticated asset. Re-derived per call (default 15-minute expiry,
 * matching the old Firebase Storage signed-URL window) rather than
 * stored.
 *
 * resourceType MUST be the actual Cloudinary resource type the asset
 * was stored under ("image" or "raw" in this app — PDFs upload as
 * "image" since Cloudinary can rasterize them; Office documents upload
 * as "raw"). "auto" is valid for the UPLOAD endpoint (Cloudinary picks
 * the type for you) but is NOT a valid value when generating a fetch/
 * download URL afterward — you have to know which type it actually
 * became. This is why document_versions now stores resourceType
 * alongside fileUrl (see createDocumentVersion in lib/firebase/admin.ts)
 * rather than re-deriving or guessing it at download time.
 */
export function getAuthenticatedAssetUrl(
  publicId: string,
  resourceType: "image" | "raw",
  options: { format?: string; expiresInSeconds?: number } = {}
): string {
  ensureConfigured();

  const expiresAt = Math.floor(Date.now() / 1000) + (options.expiresInSeconds ?? 15 * 60);

  return cloudinary.utils.private_download_url(publicId, options.format ?? "", {
    type: "authenticated",
    expires_at: expiresAt,
    resource_type: resourceType,
  });
}

/**
 * Builds a PDF-to-image preview URL — Cloudinary can rasterize a page
 * of an uploaded PDF on the fly via URL transformation, which is what
 * makes in-app PDF preview possible without a separate
 * LibreOffice/headless-browser conversion pipeline (the kind of infra
 * §6 of the original spec explicitly deferred).
 *
 * HONEST TRADE-OFF, not hidden: this uses cloudinary.url() with
 * sign_url: true, NOT private_download_url(). The two are different:
 * private_download_url() (used by getAuthenticatedAssetUrl above)
 * produces a URL with a true expires_at timestamp Cloudinary enforces
 * server-side, but its API has no parameter for applying a
 * transformation (page selection, format conversion) — it can only
 * fetch the original file. cloudinary.url() with sign_url DOES support
 * transformations, but the signature it produces has NO time-based
 * expiry — it's a permanent signed URL for that exact public_id +
 * transformation combination, valid until you revoke/regenerate
 * Cloudinary credentials. It still cannot be tampered with (changing
 * any parameter invalidates the signature) and the asset is still
 * type: "authenticated" (not publicly listable/guessable), but it is
 * NOT short-lived the way the actual file download is.
 *
 * If GIN/DBG needs short-lived PDF preview URLs specifically, the real
 * fix is enabling Cloudinary's Token-Based Authentication (auth_token
 * option, a separate signing key configured in the Cloudinary
 * dashboard) — that's a dashboard configuration step this code cannot
 * do on your behalf, which is why it isn't used here by default.
 */
export function getPdfPagePreviewUrl(publicId: string, page: number = 1): string {
  ensureConfigured();

  return cloudinary.url(publicId, {
    resource_type: "image",
    type: "authenticated",
    sign_url: true,
    format: "jpg",
    page,
  });
}

/**
 * Returns the total number of pages in a PDF asset stored on Cloudinary.
 * Uses the Admin API's resource() method with `pages: true` to include
 * multi-page metadata. Falls back to 1 if the information is unavailable.
 */
export async function getPdfPageCount(publicId: string): Promise<number> {
  ensureConfigured();

  try {
    const resource = await cloudinary.api.resource(publicId, {
      pages: true,
      type: "authenticated",
      resource_type: "image",
    });

    // Cloudinary may return `pages` as a number (page count) or an array
    // of page objects, depending on the plan/response version. Check both.
    if (typeof resource.pages === "number" && resource.pages >= 1) {
      return resource.pages;
    }
    if (Array.isArray(resource.pages) && resource.pages.length >= 1) {
      return resource.pages.length;
    }
    if (typeof resource.nb_pages === "number" && resource.nb_pages >= 1) {
      return resource.nb_pages;
    }

    console.warn(
      "getPdfPageCount: no page count found in Cloudinary response for:",
      publicId,
      "— response keys:",
      Object.keys(resource)
    );
    return 1;
  } catch (err) {
    console.error("Failed to get PDF page count for:", publicId, err);
    return 1;
  }
}

/**
 * Deletes an asset from Cloudinary. Used only if a document_versions
 * row creation fails AFTER the file already uploaded (cleanup), never
 * as a general-purpose delete — uploaded revisions are append-only per
 * §4's append-only model; this is not a "delete a revision" feature.
 */
export async function deleteUploadedAsset(publicId: string): Promise<void> {
  ensureConfigured();
  await cloudinary.uploader.destroy(publicId, { type: "authenticated", resource_type: "auto" });
}
